language: generic

#For Ubuntu Trusty (14.04 LTS)
sudo: required
dist: trusty

matrix:
  include:
    - python: "2.7"
      env: GL="GT"
    - python: "2.7"
      env: GL="IG"
    - python: "2.7"
      env: GL="NX"
    - python: "3.5"
      env: GL="GT"
    - python: "3.5"
      env: GL="IG"
    - python: "3.5"
      env: GL="NX"
  fast_finish: true

cache:
  - apt
  - pip

before_install:
  - echo $PATH
  
  # get repository for clang-3.6 stuff (including clang-format-3.6)
  - sudo sh -c 'echo -n "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main\n" >> /etc/apt/sources.list'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  # add ppa for gcc>4.9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo sh -c 'echo -n "deb http://downloads.skewed.de/apt/trusty trusty universe\n" >> /etc/apt/sources.list'
  - sudo sh -c 'echo -n "deb-src http://downloads.skewed.de/apt/trusty trusty universe\n" >> /etc/apt/sources.list'
  - gpg --keyserver 'http://pgp.skewed.de:11371/pks/lookup?op=get&search=0x612DEFB798507F25' --recv-key 98507f25
  - gpg -a --export 98507F25 | sudo apt-key add -
  # update package repository status (-qq is more quiet)
  - sudo rm -rf /var/lib/apt/lists/*
  - ls /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  # remove any obsolete libraries
  - sudo apt-get autoremove

  # requirements for building + installing scipy
  - sudo apt-get install -y build-essential gcc-4.9 autoconf automake libtool libltdl7-dev libreadline6-dev libncurses5-dev libgsl0-dev python-all-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libxml2-dev
  # Install pip and cython
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py
  - sudo pip install -U setuptools
  - sudo pip install -U nose2
  - sudo pip install -U matplotlib
  - pip install --user cython==0.23.4
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install -y python-scipy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then sudo apt-get install -y python3-scipy; fi
  # MPI
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
  # install graph-tool and igraph
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install -y python-graph-tool; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then sudo apt-get install -y python3-graph-tool; fi
  - wget http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz
  - tar -zxvf igraph-0.7.1.tar.gz && cd igraph-0.7.1
  - ./configure && make && sudo make install
  - cd .. && rm -R igraph-0.7.1
  # static code analysis
  - sudo apt-get install -y libllvm3.6 clang-format-3.6 vera++

install: sudo pip install -e ".[nx,ig]"

script: python src/nngt/testing/__init__.py $GL

